// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cabecera: typeof import('./components/Cabecera.vue')['default']
    InaplicablesComponent: typeof import('./components/InaplicablesComponent.vue')['default']
    IssueTags: typeof import('./components/IssueTags.vue')['default']
    LoadingComponent: typeof import('./components/LoadingComponent.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    Reporte: typeof import('./components/reporte.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteForm: typeof import('./components/SiteForm.vue')['default']
    TableForm: typeof import('./components/TableForm.vue')['default']
    TableView: typeof import('./components/TableView.vue')['default']
    TableView2: typeof import('./components/TableView2.vue')['default']
  }
}

export {}
